version: '3'

services:

  shard1svr1:
    hostname: shard1svr1
    container_name: local-shard1-server1
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 50001:27017
    networks:
      - mongodb-net
    volumes:
      - shard1svr1:/data/db
    restart: always

  shard1svr2:
    depends_on:
      - shard1svr1
    hostname: shard1svr2
    container_name: local-shard1-server2
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 50002:27017
    networks:
      - mongodb-net
    volumes:
      - shard1svr2:/data/db
    restart: always

  shard1svr3:
    depends_on:
      - shard1svr2
    hostname: shard1svr3
    container_name: local-shard1-server3
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 50003:27017
    networks:
      - mongodb-net
    volumes:
      - shard1svr3:/data/db
    restart: always

  shard1setup:
    depends_on:
      - shard1svr1
      - shard1svr2
      - shard1svr3
    container_name: shard1-setup
    networks:
      - mongodb-net
    image: mongo
    volumes:
      - .:/scripts
    entrypoint: ["bash", "/scripts/shard1-setup.sh"]
    restart: "no"

volumes:
  shard1svr1: {}
  shard1svr2: {}
  shard1svr3: {}

networks:
  mongodb-net:
    external:
      name: custom_network
